project:
  type: manuscript
  output-dir: docs
manuscript:
  article: manuscript.qmd

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  # docx: 
  #   notebook-links: false
  agu-pdf: 
    notebook-links: false
    header-includes:
      - \usepackage{annotate-equations}



